export const characters = [
    {
        name: "Hoid",
        linkID: "hoid",
        imgSrc: "images/300px-Worldsinger_by_Ari_Ibarra.jpg",
        homePlanet: "Yolen",
        bookAppearances: "Mistborn Era 1 & 2, The Stormlight Archive, Warbreaker, Elantris, The Sunlit Man, and various cameos",
        magicSystems: "Yolish Lightweaving, Rosharan Lightweaving, Awakening, Allomancy, Elantrian, and possibly others.",
        alliances: "Worldsinger",
        otherInfo: "Uses many aliases, including Wit and Dust",
        descPreview: "Hoid is one of the oldest and most enigmatic beings in the Cosmere, originating from the hidden world of Yolen. He inserts himself into major historical moments across",
        desc1: "Hoid is one of the oldest and most enigmatic beings in the Cosmere, originating from the hidden world of Yolen. He inserts himself into major historical moments across planets, often serving as a wandering storyteller, musician, or advisor. His eccentric humor masks deep knowledge and complicated emotions, and his true motivations remain partially hidden.",
        desc2: "Despite his tendency to keep people at arm’s length, Hoid forms quiet connections with individuals he meets, guiding or nudging them when it suits a greater purpose. Over time, he has acquired access to multiple magic systems, though he avoids direct violence due to supernatural restrictions. His presence is a thread weaving through the entire Cosmere.",
    },
    {
        name: "Kelsier",
        linkID: "kelsier",
        imgSrc: "images/300px-Cognitive_Shadow_Kelsier.jpg",
        homePlanet: "Scadrial",
        bookAppearances: "Mistborn Era 1 & 2, Mistborn: Secret History",
        magicSystems: "Allomancy (Mistborn)",
        alliances: "Leader of the Skaa rebellion, Founder of the Ghostbloods",
        otherInfo: "",
        descPreview: "Kelsier began as a gifted thief whose life was shaped by tragedy, especially the death of his wife. His time in the Pits of Hathsin awakened his Allomancy and transformed",
        desc1: "Kelsier began as a gifted thief whose life was shaped by tragedy, especially the death of his wife. His time in the Pits of Hathsin awakened his Allomancy and transformed him into a bold, charismatic revolutionary known as the Survivor of Hathsin. His reckless confidence and fierce belief in hope rallied the oppressed skaa of the Final Empire.",
        desc2: "Even after his death, Kelsier’s determination and refusal to fade from history allow him to influence events on Scadrial and beyond. His curiosity about the greater Cosmere and relentless will to survive set him apart as one of its most persistent and disruptive figures."
    },
    {
        name: "Vin",
        linkID: "vin",
        imgSrc: "images/The_Ascendant_Warrior.jpg",
        homePlanet: "Scadrial",
        bookAppearances: "Mistborn Era 1",
        magicSystems: "Allomancy (Mistborn), Hemalurgy",
        alliances: "Kelsier's Crew, New Empire",
        otherInfo: "",
        descPreview: "Vin begins as a street orphan skilled at avoiding attention and betrayal. Her discovery as a powerful Mistborn thrusts her into the center of a rebellion aiming to",
        desc1: "Vin begins as a street orphan skilled at avoiding attention and betrayal. Her discovery as a powerful Mistborn thrusts her into the center of a rebellion aiming to overthrow a thousand-year empire. Her introverted and suspicious nature slowly softens as she learns to trust those around her.",
        desc2: "As she grows into her powers, Vin becomes a nearly unstoppable force who seeks truth, justice, and connection in a harsh world. Her emotional journey parallels Scadrial’s transformation from oppression to hope."
    },
    {
        name: "Elend Venture",
        linkID: "elend",
        imgSrc: "images/300px-Elend_Shuravf.jpg",
        homePlanet: "Scadrial",
        bookAppearances: "Mistborn Era 1",
        magicSystems: "Allomancy",
        alliances: "New Empire",
        otherInfo: "",
        descPreview: "Elend is a nobleman with a gentle temperament and a love for books and political philosophy. Even in a corrupt society, he imagines a more ideal and equitable form of",
        desc1: "Elend is a nobleman with a gentle temperament and a love for books and political philosophy. Even in a corrupt society, he imagines a more ideal and equitable form of government. His relationship with Vin pushes him to take responsibility for the world around him.",
        desc2: "Though not initially a powerful Allomancer or a strong leader, Elend grows into both roles as he faces apocalyptic threats. His idealism, tempered by difficult choices, defines his impact on Scadrial’s future."
    },
    {
        name: "Kaladin Stormblessed",
        linkID: "kaladin",
        imgSrc: "images/The_Next_Ideal.png",
        homePlanet: "Roshar",
        bookAppearances: "The Stormlight Archive Books",
        magicSystems: "Surgebinding (Windrunner)",
        alliances: "Knights Radiant, Bridge Four",
        otherInfo: "",
        descPreview: "Kaladin begins life as a surgeon’s son but becomes a soldier, slave, and eventually a leader of men. His deep sense of responsibility and fierce desire to protect others",
        desc1: "Kaladin begins life as a surgeon’s son but becomes a soldier, slave, and eventually a leader of men. His deep sense of responsibility and fierce desire to protect others define his character. Though burdened by depression, he continually pushes forward for the sake of those who rely on him.",
        desc2: "Through his bond with Sylphrena, Kaladin gains the powers of a Windrunner, granting him the ability to manipulate gravity and pressure. His journey explores trauma, leadership, and the struggle to hold onto hope in moments of darkness."
    },
    {
        name: "Shallan Davar",
        linkID: "shallan",
        imgSrc: "images/Whelan_Stormlight_Shallan.jpg",
        homePlanet: "Roshar",
        bookAppearances: "The Stormlight Archive",
        magicSystems: "Surgebinding (Lightweaver)",
        alliances: "Knights Radiant, Ghostbloods (formerly)",
        otherInfo: "",
        descPreview: "Shallan is a brilliant artist with a traumatic past and a personality shaped by layers of self-deception. Her Lightweaving abilities complement her natural",
        desc1: "Shallan is a brilliant artist with a traumatic past and a personality shaped by layers of self-deception. Her Lightweaving abilities complement her natural observational skills, allowing her to recreate what she sees—or imagines—with stunning accuracy.",
        desc2: "Throughout her journey, Shallan confronts painful truths while juggling political intrigue, espionage, and Radiant responsibilities. Her story centers on identity, perception, and the healing power of creativity and truth."
    },
    {
        name: "Dalinar Kholin",
        linkID: "dalinar",
        imgSrc: "images/300px-Dalinar.jpg",
        homePlanet: "Roshar",
        bookAppearances: "The Stormlight Archive",
        magicSystems: "Surgebinding (Bondsmith)",
        alliances: "Knights Radiant, The Coalition",
        otherInfo: "",
        descPreview: "Dalinar is a former warlord known in his youth as the Blackthorn, feared for his unmatched brutality in battle. Visions from the deceased Shard Honor push him toward a",
        desc1: "Dalinar is a former warlord known in his youth as the Blackthorn, feared for his unmatched brutality in battle. Visions from the deceased Shard Honor push him toward a very different path: one of peace, unity, and moral responsibility.",
        desc2: "As a Bondsmith, Dalinar channels extraordinary spiritual power and serves as a unifying force for the Radiants and the world. His transformation from destroyer to builder forms a central emotional arc of the Stormlight Archive."
    },
    {
        name: "Adolin Kholin",
        linkID: "adolin",
        imgSrc: "images/300px-Adolin.jpg",
        homePlanet: "Roshar",
        bookAppearances: "The Stormlight Archive",
        magicSystems: "Shardbearer, Unoathed",
        alliances: "Knights Radiant, The Coalition",
        otherInfo: "",
        descPreview: "Adolin is a charismatic prince and master duelist who relies on skill and empathy rather than magical power. He is genuinely kind, supportive, and driven to do what",
        desc1: "Adolin is a charismatic prince and master duelist who relies on skill and empathy rather than magical power. He is genuinely kind, supportive, and driven to do what he believes is right, even when it conflicts with cultural expectations.",
        desc2: "His relationship with Maya, a deadeye spren, marks one of the most unusual developments in Roshar’s magical landscape. Adolin’s journey emphasizes compassion, integrity, and challenging tradition."
    },
    {
        name: "Sigzil",
        linkID: "sigzil",
        imgSrc: "images/300px-Sigzil_Portrait_by_Marie_Seeberger.jpg",
        homePlanet: "Roshar",
        bookAppearances: "The Stormlight Archive, The Sunlit Man",
        magicSystems: "Surgebinding (Windrunner, Skybreaker), Dawnshard Exist",
        alliances: "Bridge Four, Knights Radiant",
        otherInfo: "Other names include Nomad and Zellion.",
        descPreview: "Sigzil begins as a thoughtful scribe in Bridge Four, shaped by his experiences with slavery, strict rules, and deep guilt. His analytical mind contrasts with Kaladin’s",
        desc1: "Sigzil begins as a thoughtful scribe in Bridge Four, shaped by his experiences with slavery, strict rules, and deep guilt. His analytical mind contrasts with Kaladin’s instinctive leadership, but he becomes a valued companion and later a Knight Radiant in his own right.",
        desc2: "By the era of The Sunlit Man, Sigzil has transformed into Nomad, a weary worldhopper burdened with unstable powers and a painful past. His story is one of escape, redemption, and perseverance despite overwhelming odds."
    },
    {
        name: "Tanavast",
        linkID: "tanavast",
        imgSrc: "images/Honor_Endsheet.jpeg.jpeg",
        homePlanet: "Yolen",
        bookAppearances: "The Stormlight Archive",
        magicSystems: "Shard (Honor)",
        alliances: "Heralds",
        otherInfo: "",
        descPreview: "Tanavast was the original Vessel of Honor and shaped the foundational principles behind the Knights Radiant and their oaths. Known for passion and nobility, he viewed",
        desc1: "Tanavast was the original Vessel of Honor and shaped the foundational principles behind the Knights Radiant and their oaths. Known for passion and nobility, he viewed bonds and commitments as sacred forces that tied people and worlds together.",
        desc2: "After his death to the Shard Odium, fragments of his consciousness survived in visions shown to Dalinar. These remnants reveal a god exhausted by war but desperate to prepare humankind for what was coming. His legacy permeates Roshar’s spiritual and magical systems."
    },
    {
        name: "Rashek (The Lord Ruler)",
        linkID: "rashek",
        imgSrc: "images/300px-The_Lord_Ruler_by_Nevena_Jevtic.jpg",
        homePlanet: "Scadrial",
        bookAppearances: "Mistborn: The Final Empire",
        magicSystems: "Allomancy (Mistborn), Feruchemy, Hemalurgy",
        alliances: "The Final Empire, Steel Ministry",
        otherInfo: "",
        descPreview: "Rashek was originally a Terrisman who rose to godlike power after a series of dramatic events led him to take control of immense Investiture. He reshaped Scadrial and",
        desc1: "Rashek was originally a Terrisman who rose to godlike power after a series of dramatic events led him to take control of immense Investiture. He reshaped Scadrial and ruled for a thousand years as the Lord Ruler, maintaining an oppressive but strangely stable empire.",
        desc2: "Though tyrannical, Rashek believed he was preserving the world from destruction, even if it required brutality. His mastery of Feruchemy and Allomancy made him one of the most powerful individuals in Cosmere history, and his legacy remains a complex blend of fear, awe, and reluctant respect."
    },
]